spring:
    application:
        name: backend
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/expense_data?createDatabaseIfNotExist=true
        username: root
        password: ${MYSQL_PASS}
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update

            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
            show_sql: false
        sql:
            init:
                mode: never
    backend:
        key: ${SECRET_KEY}